### ISSUE TITLE
Databricks provisioning fails when creating the solution

### ISSUE THREAD

**Issue by isinghrana** [Azure-Samples/streaming-at-scale#116]
I encountered failure in creating the Eventhub Databricks CosmosDb solution - https://github.com/Azure-Samples/streaming-at-scale/blob/main/eventhubs-databricks-cosmosdb/create-solution.sh

I have narrowed down the issue that Databricks ARM Templates do not exist at the location used by the script.

https://github.com/Azure-Samples/streaming-at-scale/blob/main/components/azure-databricks/create-databricks.sh
Line#22 on above script references a broken link - https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-databricks-all-in-one-template-for-vnet-injection/azuredeploy.json

**Comment by isinghrana** [comment]
Found the updated link to the Azure Databricks ARM Template so the script needs to point to this location - https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection/azuredeploy.json

**Comment by algattik** [comment]
Thanks for reporting.
