### ISSUE TITLE
Permission Denied on 05-report-throughput.sh

### ISSUE THREAD

**Issue by markjbrown** [Azure-Samples/streaming-at-scale#42]
I am running through the eventhubs-streamanalytics-cosmosdb sample and get this error below when I run the create-solution.sh script. Any idea how I can fix?

CC @yorek 

thanks.

***** [M] Starting METRICS reporting
./create-solution.sh: line 208: ./05-report-throughput.sh: Permission denied
There was an error, execution halted
Error at line 208

**Comment by yorek** [comment]
Could it be that you are running from a Mac or Ubuntu (Native)?

**Comment by markjbrown** [comment]
Running in WSL.

**Comment by yorek** [comment]
Interesting, let me check

**Comment by yorek** [comment]
Which sample are you testing?

**Comment by markjbrown** [comment]
this one https://github.com/Azure-Samples/streaming-at-scale/tree/master/eventhubs-streamanalytics-cosmosdb

**Comment by yorek** [comment]
This can be fixed by making sure permission are correctly set on all shell files. Run the following script in the root:

`find -name "*.sh" | xargs chmod +x`

**Comment by markjbrown** [comment]
awesome. Thanks Davide!
