### ISSUE TITLE
Misspelling of the word function

### ISSUE THREAD

**Issue by griffinbird** [Azure-Samples/streaming-at-scale#93]
Look for start of sentence.. "As you'll notice when using funciont "Test1". Function is misspelt.

**Comment by yorek** [comment]
Can you point out in which file? Thanks.

**Comment by griffinbird** [comment]
@yorek sorry, took me a while to find it.. here is the link to the section with the spelling mistake. https://github.com/Azure-Samples/streaming-at-scale/tree/master/eventhubs-functions-cosmosdb#cosmos-db
