### ISSUE TITLE
Deployment of eventhubs-streamanalytics-azuresql fails

### ISSUE THREAD

**Issue by Karl-HeinzS** [Azure-Samples/streaming-at-scale#99]
Deployment of eventhubs-streamanalytics-azuresql fails in Azure Cloud Shell with:

Error:
***** [D] Setting up DATABASE
retrieving storage connection string
deploying azure sql
. server: myiottestsql
. database: streaming
creating logical server
enabling access from Azure
deploying database db
creating file share
uploading provisioning scripts
uploading provision.sh...
Finished[#############################################################]  100.0000%
uploading db/provision.sql...
Finished[#############################################################]  100.0000%
running provisioning scripts in container instance
../components/azure-sql/create-sql.sh: line 54: uuidgen: command not found
There was an error, execution halted
Error at line 54

**Comment by algattik** [comment]
Azure Cloud Shell does not have the `uuidgen` command.

The script should check that the command is installed and fail early otherwise.
Or better, find another approach to generating names

**Comment by algattik** [comment]
Please vote for https://feedback.azure.com/forums/598699-azure-cloud-shell/suggestions/41184361-include-uuidgen-binary-in-the-image

**Comment by yorek** [comment]
Replace name generation via uuidgen with openssl
